version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - micro-network
    env_file: ./.env

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - micro-network
    env_file: ./.env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo-replica
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--username=root",
          "--password=12345",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  micro-network:
